
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-happycows-s26-14
owner: ucsb-cs156-s26
repo_name: proj-happycows-s26-14
pull_requests: [{"author":{"id":"U_kgDOCNoJ1w","is_bot":false,"login":"brianridderucsb","name":""},"headRefName":"br-announcements-frontend-admin","number":67,"title":"Added simple frontend implementation for announcements","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-14/pull/67"},{"author":{"id":"U_kgDOC5aSLg","is_bot":false,"login":"BennyZll","name":""},"headRefName":"benny-Student-Backend-2.0","number":66,"title":"Add student backend CRUD","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-14/pull/66"},{"author":{"id":"U_kgDOCVIAYQ","is_bot":false,"login":"ncontreras1","name":""},"headRefName":"Nathan-announcements-typo","number":65,"title":"Fix typo ","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-14/pull/65"},{"author":{"id":"U_kgDOCNoJ1w","is_bot":false,"login":"brianridderucsb","name":""},"headRefName":"br-announcements-backend-datetime","number":59,"title":"Add announcements frontend implementation","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-14/pull/59"},{"author":{"id":"U_kgDOCVIAYQ","is_bot":false,"login":"ncontreras1","name":""},"headRefName":"Nathan-addCourseDELETE","number":58,"title":"Add DELETE endpoint for Courses API","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-14/pull/58"},{"author":{"id":"U_kgDOCujYag","is_bot":false,"login":"AbhijeetDutta1","name":"Abhijeet Dutta"},"headRefName":"abhi-CFfrontend","number":57,"title":"Abhi added enum for cf frontend to backend interaction","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-14/pull/57"},{"author":{"id":"U_kgDOCujYag","is_bot":false,"login":"AbhijeetDutta1","name":"Abhijeet Dutta"},"headRefName":"abhi-CFreactapi","number":55,"title":"Abhi common features - add API endpoints & feature/controller/repo","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-14/pull/55"},{"author":{"id":"U_kgDOC5aSLg","is_bot":false,"login":"BennyZll","name":""},"headRefName":"benny-Form-for-Course","number":52,"title":"Add Form component for Course","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-14/pull/52"}]
